name: Decrypt CI

on:
  workflow_dispatch:
    inputs:
      data_csv:
        type: string
        default: 'Algo,Key,Decrypted,Encrypted,EncryptionError'
        description: CSV Data for Decryption
      lang:
        type: string
        default: 'JavaScript'
        description: CSV Data for Decryption

jobs:
  decrypt:
    name: Decrypt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Decrypt values from ${{ inputs.lang }} encryption
      run: |
        echo "${{ inputs.data_csv }}" | go run main.go decrypt
